name: Notify Slack on PR Open

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR link to Slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: C09E8ELLDT4 # Slack channel ID
          payload: |
            {
              "text": "🚀 A new Pull Request is ready for review!",
              "attachments": [
                {
                  "color": "#36a64f",
                  "title": "${{ github.event.pull_request.title }}",
                  "title_link": "${{ github.event.pull_request.html_url }}",
                  "text": "Author: *${{ github.actor }}*\nBranch: `${{ github.head_ref }}`",
                  "footer": "GitHub → Slack Automation"
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
